### ISSUE TITLE
vue-cli 3 써보기

### ISSUE THREAD

**Issue by ChangJoo-Park** [JuhoKang/vue-webpack-ex#1]
아직 프로젝트 본격적으로 시작한건 아닌거 같은데 vue-cli 2 + webpack 템플릿으로 만든 프로젝트로 보여서 이슈 남겨

https://github.com/vuejs/vue-cli

```
npm install -g @vue/cli
```

아직 베타이긴 한데 3버전으로 시작하는게 훨씬 나을거야
webpack 등 자바스크립트 도구들에 익숙하면 상관없긴하지만 굳이 이전 버전을 쓸 필요가 없거든

**Comment by ChangJoo-Park** [comment]
https://marketplace.visualstudio.com/items?itemName=changjoo-park.vscode-vue-devpack

코드 에디터로 Visual Studio Code를 쓰면 이거 쓰면 대부분 개발하는데 불편함이 없을거야

**Comment by JuhoKang** [comment]
@ChangJoo-Park  감사합니다 ㅠㅠ 바로 써봐야겠어요. 사실 프론트엔드 웹프레임워크 감을 잘 못잡고 있어서 좀  고생하고 있습니다. 보통 템플릿으로 html찍어서 jQuery + 라이브러리 사용해서 개발했거든요. 프레임워크외에 라이브러리를 붙여 쓰는거에서 좀 고생하고 있는데 어찌저찌 되고는 있는것 같습니다. 코드에디터 확장팩 팁도 감사합니다 vetur만 켜뒀는데 많네요 ㅎ.ㅎ

**Comment by ChangJoo-Park** [comment]
막히면 물어봐 ㅋㅋ

**Comment by JuhoKang** [comment]
@ChangJoo-Park 어떻게 연락드리는게 편하십니까 ㅎ.ㅎ

**Comment by ChangJoo-Park** [comment]
https://vuejs-korea.signup.team

여기서 changjoo-park 아이디 쓰는사람 찾아봐 ㅋㅋ
